@extends('frontend.includes.app')
@section('main-content')

<!-- ======= Breadcrumbs ======= -->
<div class="breadcrumbs d-flex align-items-center" style="background-image: url('{{asset('frontend/assets/img/breadcrumbs-bg.jpg')}}');">
    <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>ACCOUNTING</h2>
        <ol>
            <li><a href="{{route('index')}}">Home</a></li>
            <li>INSIGHTS</li>
            <li>Accounting</li>
        </ol>

    </div>
</div><!-- End Breadcrumbs -->

<section id="project-details" class="project-details">
    <div class="container" data-aos="fade-up" data-aos-delay="100">



        <div class="row justify-content-between gy-4 mt-4">

            <div class="col-lg-8">
                <div class="portfolio-description">
                    <h2>Accounting</h2>
                    <p>
                       <strong> What is Accounting? </strong>
                    </p>
                    <p>
                        Accounting is one of the key functions for almost any business. It may be handled by a bookkeeper or an accountant at a small firm, or by sizable finance departments with dozens of employees at larger companies. The reports generated by various streams of accounting, such as cost accounting and managerial accounting, are invaluable in helping management make informed business decisions.
                    </p>
                    <br>
                    <p>
                        <strong> What are the advantages of Accounting? </strong>
                    </p>
                    <p>Accounting plays a key role in running a business because it helps you track income and expenditures, ensure statutory compliance, and provide investors, management, and government with quantitative financial information which can be used in making business decisions.
                    </p>



                </div>
            </div>
        </div>
    </div>
</section>

@endsection